#!/usr/bin/env bash

set -xe

mkdir -p deps

if [ -d "deps/nfnl" ]; then
	(cd deps/nfnl && git pull)
else
	git clone https://github.com/Olical/nfnl.git deps/nfnl
fi

SRC_DIR=deps/nfnl/lua/nfnl \
	PROJECT=dotnet-squire \
	DEST_DIR=lua/dotnet-squire \
	./deps/nfnl/script/embed-library
